#!/bin/bash

# DARTBUG: http://code.google.com/p/dart/issues/detail?id=5460
# I feel I shouldn't have to exclude unittest

libs=`ls lib/*.dart`
cmd="dartdoc
--omit-generation-time
--out build/doc
--verbose
--exclude-lib unittest
$libs"
echo $cmd
exec $cmd
