#!/bin/bash

# DARTBUG: http://code.google.com/p/dart/issues/detail?id=5460
# I feel I shouldn't have to exclude unittest

# NOTE: assumes 'current dir' is the root of the project

libs=`ls lib/*.dart | grep -v test`
cmd="dartdoc
--omit-generation-time
--out build/doc
--verbose
$libs"
echo $cmd
exec $cmd
