#!/bin/bash

# DARTBUG: http://code.google.com/p/dart/issues/detail?id=5460
# I feel I shouldn't have to exclude unittest

# DARTBUG: http://code.google.com/p/dart/issues/detail?id=5218
# seems we can't get anything working here since we use args package.

# NOTE: assumes 'current dir' is the root of the project

libs=`ls lib/*.dart`
cmd="dartdoc
--omit-generation-time
--out build/doc
--verbose
--exclude-lib unittest
$libs"
echo $cmd
exec $cmd
